spring:
  mail:
    #配置smtp服务主机地址
    # qq邮箱为smtp.qq.com          端口号465或587
    # sina    smtp.sina.cn
    # aliyun  smtp.aliyun.com
    # 163     smtp.163.com       端口号465或994
    host: smtp.qq.com
    #发送者邮箱
    username: 2516743200@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: mjobgbdmnccwdjjj
    #端口号465或587
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

  profiles:
    active: dev2
---
spring:
  config:
    activate:
      on-profile: dev
httpport: 80
server:
  port: 8080
  ##  address: 192.168.0.4
  ssl:
    key-store-password: 045u78eqn9l
    keyStoreType: PKCS12
    key-alias: william.fit
    key-store: classpath:william.fit.pfx
---
spring:
  config:
    activate:
      on-profile: dev1
httpport: 81
server:
  port: 8081
  #  address: 192.168.0.4
  ssl:
    key-store-password: 045u78eqn9l
    keyStoreType: PKCS12
    key-alias: william.fit
    key-store: classpath:william.fit.pfx
---
spring:
  config:
    activate:
      on-profile: dev2
httpport: 82
server:
  port: 8082
#  address: 192.168.39.204
  ssl:
    key-store-password: 045u78eqn9l
    keyStoreType: PKCS12
    key-alias: william.fit
    key-store: classpath:william.fit.pfx
---


mybatis-plus:
#  mapper-locations: classpath:com.william.collegeapartmentsbacke.mapper/**/*.xml
  type-aliases-package: com.william.collegeapartmentsbacke.pojo.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#
logging:
  level:
    com.william.collegeapartmentsbacke.mapper : debug
    com.baomidou.mybatisplus: debug
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1GB
  datasource: #主数据库
    url: jdbc:mysql://121.41.36.101:13308
    TimeZone: Asia/Shanghai
    username: root
    password: CollegeApartments!@#123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      test-on-borrow: true


zhrc:
  jwt:
    secret-key: 7bd78bq99bee54deec255986ba95d654
    ttl: 86400000

    token-name: Authorization
  wechat:
    appid: wx3b5ec6e4e336f19e
    secret: adb45243c65766fca8e5c94454a39ef0
localFileUrl : D:/back/static/
mapFileUrl : /static/
defaults:
  password: "123456"
  userLevel: "1"
  avatarUrl: "https://william.fit:8082/static/2ff45385-e749-4205-ba16-02e1a0ea7ba6.jpg"

