server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.william.collegeapartmentsbacke.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://121.41.36.101:13308
    username: root
    password: CollegeApartments!@#123
    driver-class-name: com.mysql.cj.jdbc.Driver


